default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: stark_development

test:
  <<: *default
  database: stark_test

production:
  <<: *default
  database: stark_production
  username: stark
  password:
